#!/bin/bash

set -e

if [[ -n "${{cookiecutter.caps_project}}_DEBUG" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Publishes {{cookiecutter.project}} image to ECR. Expects {{cookiecutter.caps_project}}_ECR_IMAGE env var to be set to <ecr_repo_name>:<tag_name>
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
        exit
    fi

    IMAGE_NAME="{{cookiecutter.project}}:latest"
    ACCOUNT_ID=$(aws sts get-caller-identity --output text --query 'Account')
    AWS_REGION="us-east-1"

    aws ecr get-login --no-include-email --region ${AWS_REGION} | bash;
    docker tag ${IMAGE_NAME} \
        ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${{cookiecutter.caps_project}}_ECR_IMAGE
    docker push \
        ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${{cookiecutter.caps_project}}_ECR_IMAGE
fi
